#!/bin/sh -e

if [ -z "$2" ]; then
  echo "Usage: $0 partial-manifest.json /nix/store/..." > /dev/stderr
  exit 1
fi

exec=$(realpath "$2")
json=$(realpath "$1")
temp=$(mktemp -d)
this=$(realpath "$0")

cd "$temp"

jq -s add "$(dirname "$this")/manifest.json" "$json" | jq --arg _ "$exec" '.command = $_' > manifest.json

for path in $(nix-store -qR "$exec"); do
  cp --parents -r "$path" .
done

chmod -R +w .

# I'm so excited, I feel like I haven't been quite so happy with anything
# I've ever done in my life. Hope you enjoy what comes next.
find . -type f -exec sed -i s:/nix/store:/app/store:g {} \;

flatpak-builder build manifest.json --install

rm -r "$temp"
